apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ include "coin-ops.namespace" . }}
  labels:
    {{- include "coin-ops.commonLabels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
