{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "coin-ops.namespace" . }}
  labels:
    {{- include "coin-ops.commonLabels" . | nindent 4 }}
{{- end }}

