{{- if .Values.secret.create }}
{{- $root := . -}}
{{- range $namespace := list (include "coin-ops.appNamespace" $root) (include "coin-ops.workersNamespace" $root) (include "coin-ops.dataNamespace" $root) | uniq }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.Values.secret.name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "coin-ops.commonLabels" $root | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := $root.Values.secret.stringData }}
  {{ $key }}: {{ tpl ($value | toString) $root | quote }}
{{- end }}
---
{{- end }}
{{- end }}
