- name: install redis packages
  ansible.builtin.apt:
    name: 
      - redis-server
    state: present
    update_cache: true

- name: ensure redis is running
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: true

# to allow connection
- name: configure redis bind address
  become: true
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind '
    line: 'bind 127.0.0.1 {{redis_host}}'
  notify: reload redis


#   - 1 task was completed -> restart redis set to queue
#  - 2 task was completed ->a again restart redis set to queue
#  in the restart redis will be only completed once


- name: set redis password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^#?\s*requirepass\s*'
    line: 'requirepass {{redis_password}}'
  notify: reload redis