locals {
  bastion = var.instances[var.bastion_name]

  ssh_bastion_alias = "${var.name_prefix}-bastion"

  runtime                      = var.runtime
  runtime_mode                 = try(local.runtime.mode, "external")
  database_managed             = try(local.runtime.database.managed, false)
  db_host                      = local.database_managed ? try(local.runtime.database.host, "") : var.instances[var.db_name].private_ip
  db_port                      = try(local.runtime.database.port, 5432)
  db_name                      = try(local.runtime.database.name, "cognitor")
  db_user                      = try(local.runtime.database.user, "cognitor")
  queue_backend                = try(local.runtime.queue.backend, "")
  queue_name                   = try(local.runtime.queue.name, "")
  queue_url                    = try(local.runtime.queue.url, "")
  pubsub_topic                 = try(local.runtime.queue.topic, "")
  pubsub_sub                   = try(local.runtime.queue.subscription, "")
  aws_region                   = try(local.runtime.aws_region, "")
  aws_profile                  = try(local.runtime.aws_profile, "")
  gcp_project_id               = try(local.runtime.gcp_project_id, "")
  session_backend              = try(local.runtime.sessions.backend, "")
  cache_backend                = try(local.runtime.cache.backend, "")
  cache_host                   = try(local.runtime.cache.host, "")
  cache_port                   = try(local.runtime.cache.port, 6379)
  redis_url                    = try(local.runtime.cache.redis_url, local.cache_host != "" ? "redis://${local.cache_host}:${local.cache_port}/0" : "")
  db_password_secret_ref       = try(var.secret_refs.db_password.secret_id, try(var.secret_refs.db_password.name, ""))
  rabbitmq_password_secret_ref = try(var.secret_refs.rabbitmq_password.secret_id, try(var.secret_refs.rabbitmq_password.name, ""))
  ghcr_token_secret_ref        = try(var.secret_refs.ghcr_token.secret_id, try(var.secret_refs.ghcr_token.name, ""))

  ssh_config = join("\n\n", concat(
    [<<-EOT
    Host ${local.ssh_bastion_alias}
      HostName ${local.bastion.public_ip}
      User ${var.ssh.user}
      IdentityFile ${var.ssh.private_key_path}
      IdentitiesOnly yes
      UserKnownHostsFile ${var.known_hosts_file}
      StrictHostKeyChecking accept-new
    EOT
    ],
    [
      for name, instance in var.instances : <<-EOT
      Host ${var.name_prefix}-${name}
        HostName ${instance.private_ip}
        User ${var.ssh.user}
        IdentityFile ${var.ssh.private_key_path}
        IdentitiesOnly yes
        ProxyJump ${local.ssh_bastion_alias}
        UserKnownHostsFile ${var.known_hosts_file}
        StrictHostKeyChecking accept-new
      EOT
      if name != var.bastion_name
    ]
  ))

  app_inventory_lines = [
    for name in var.app_names :
    "${var.name_prefix}-${name} ansible_host=${var.instances[name].private_ip}"
  ]

  db_inventory_block = local.database_managed ? "" : <<-EOT

  [db]
  ${var.name_prefix}-${var.db_name} ansible_host=${var.instances[var.db_name].private_ip}
  EOT

  db_vars_block = local.database_managed ? "" : <<-EOT

  [db:vars]
  coinops_ssh_common_args='-o ProxyJump=${local.ssh_bastion_alias} -o UserKnownHostsFile=${var.known_hosts_file} -o StrictHostKeyChecking=accept-new'
  EOT

  cloud_children = compact(["bastion", "app", local.database_managed ? "" : "db"])

  ansible_inventory = <<-EOT
  # Generated by Terraform from config/lab.yaml plus cloud runtime outputs.
  # Do not edit this file directly; change config/lab.yaml, apply, then regenerate outputs.

  [bastion]
  ${var.name_prefix}-${var.bastion_name} ansible_host=${local.bastion.public_ip}

  [app]
  ${join("\n", local.app_inventory_lines)}${local.db_inventory_block}

  [cloud:children]
  ${join("\n", local.cloud_children)}

  [cloud:vars]
  coinops_ansible_user=${var.ssh.user}
  coinops_ssh_private_key_file=${var.ssh.private_key_path}
  coinops_app_domain=${var.app_domain}
  coinops_tls_mode=off
  coinops_runtime_backend=${local.runtime_mode}
  coinops_db_host=${local.db_host}
  coinops_db_port=${local.db_port}
  coinops_db_name=${local.db_name}
  coinops_db_user=${local.db_user}
  coinops_app_url=${var.app_url}
  coinops_queue_backend=${local.queue_backend}
  coinops_queue_name=${local.queue_name}
  coinops_queue_url=${local.queue_url}
  coinops_aws_region=${local.aws_region}
  coinops_cloud_region=${local.aws_region}
  coinops_cloud_profile=${local.aws_profile}
  coinops_gcp_project_id=${local.gcp_project_id}
  coinops_pubsub_topic=${local.pubsub_topic}
  coinops_pubsub_subscription=${local.pubsub_sub}
  coinops_session_backend=${local.session_backend}
  coinops_cache_backend=${local.cache_backend}
  coinops_cache_host=${local.cache_host}
  coinops_cache_port=${local.cache_port}
  coinops_redis_url=${local.redis_url}
  coinops_db_password_secret_ref=${local.db_password_secret_ref}
  coinops_rabbitmq_password_secret_ref=${local.rabbitmq_password_secret_ref}
  coinops_ghcr_token_secret_ref=${local.ghcr_token_secret_ref}
  coinops_cloud_provider=${var.cloud}
  coinops_ssh_known_hosts_file=${var.known_hosts_file}

  [bastion:vars]
  coinops_ssh_common_args='-o UserKnownHostsFile=${var.known_hosts_file} -o StrictHostKeyChecking=accept-new'

  [app:vars]
  coinops_ssh_common_args='-o ProxyJump=${local.ssh_bastion_alias} -o UserKnownHostsFile=${var.known_hosts_file} -o StrictHostKeyChecking=accept-new'
  ${local.db_vars_block}
  EOT
}
