{{- if .Values.features.deployInfra }}
# =============================================================================
# deploy/k3s/infra/cnpg-secrets.yaml
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespaces.infra }}
  name: cnpg-app-secret
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.database.user }}"
  password: "{{ .Values.database.password }}"

---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespaces.infra }}
  name: cnpg-migration-secret
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.database.user }}"
  password: "{{ .Values.database.password }}"

{{- end }}
