{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-app-secret
  namespace: {{ .Values.namespaces.infra }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: cnpg-app-secret
    template:
      engineVersion: v2
      data:
        username: "{{ .Values.database.user }}"
        password: "{{ `{{ .db_password }}` }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: coinops-db-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.namespaces.infra }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: rabbitmq-secret
    template:
      engineVersion: v2
      data:
        rabbitmq-password: "{{ `{{ .rabbitmq_password }}` }}"
  data:
    - secretKey: rabbitmq_password
      remoteRef:
        key: coinops-rabbitmq-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: {{ .Values.namespaces.infra }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: redis-secret
    template:
      engineVersion: v2
      data:
        redis-password: "{{ `{{ .redis_password }}` }}"
  data:
    - secretKey: redis_password
      remoteRef:
        key: coinops-redis-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-migration-secret
  namespace: {{ .Values.namespaces.infra }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: cnpg-migration-secret
    template:
      engineVersion: v2
      data:
        username: "{{ .Values.database.user }}"
        password: "{{ `{{ .db_password }}` }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: coinops-db-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
  namespace: {{ .Values.namespaces.infra }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: cloudflared-secret
    template:
      engineVersion: v2
      data:
        TUNNEL_TOKEN: "{{ `{{ .tunnel_token }}` }}"
  data:
    - secretKey: tunnel_token
      remoteRef:
        key: coinops-cloudflare-token
{{- end }}
