# SPDX-License-Identifier: MIT-0
---
# vars file for k3s_coin_ops
k3s_coin_ops_docker_config_json: >-
  {{
    {
      "auths": {
        k3s_coin_ops_ghcr_server: {
          "username": k3s_coin_ops_ghcr_username,
          "password": k3s_coin_ops_ghcr_token,
          "email": k3s_coin_ops_ghcr_email,
          "auth": (k3s_coin_ops_ghcr_username ~ ":" ~ k3s_coin_ops_ghcr_token) | b64encode
        }
      }
    } | to_json
  }}
