version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/1.14.9/terraform_1.14.9_linux_amd64.zip
      - unzip -o terraform_1.14.9_linux_amd64.zip -d /usr/local/bin
      - terraform -version
  build:
    commands:
      - echo "Running terraform apply for EKS infrastructure..."
      - cd terraform
      - terraform init
      - terraform apply -auto-approve -target=module.aws_network -target=module.aws_security -target=module.aws_vm -target=module.aws_lb -target=module.aws_rds -target=module.aws_monitoring_alerting -target=module.aws_monitoring_logs -target=module.aws_monitoring_iam -target=module.aws_monitoring_ec2_alarms -target=module.aws_monitoring_alb_alarms -target=module.aws_monitoring_log_metrics -target=module.aws_monitoring_dashboard -target=module.aws_monitoring_agent -target=module.aws_eks -target=module.aws_codebuild

artifacts:
  files:
    - terraform/**/*
