server {
      listen 80;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      location /api/ {
          proxy_pass http://proxy:8080/;
      }

      location /history-api/ {
          proxy_pass http://history-api:8000/;
      }

      location / {
          try_files $uri /index.html;
      }
  }
