# SPDX-License-Identifier: MIT-0

---
# defaults file for ansible/roles/k3s_gateway
k3s_gateway_backend_group: k3s
k3s_gateway_listen_http_port: 80
k3s_gateway_listen_https_port: 443
k3s_gateway_backend_http_port: 80
k3s_gateway_backend_https_port: 443
