Vagrant.configure("2") do |config|
  config.vm.box = "defanator/ubuntu-24.04"
  config.vm.box_version = "24.04.3-20251227.1"

  config.ssh.insert_key = false
  config.ssh.private_key_path = [".ssh/vagrant_key", "~/.vagrant.d/insecure_private_key"]

  config.vm.define "database" do |node|
    node.vm.provider "vmware" do |v|
      v.vmx["memsize"] = "2048"
      v.vmx["numvcpus"] = "2"
    end

    node.vm.hostname = "database"
    node.vm.network "private_network", ip: "10.10.1.6"
    node.vm.network "forwarded_port", guest: 22, host: "2205", id: "ssh", auto_correct: true

    node.vm.synced_folder ".", "/vagrant"

    node.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.galaxy_role_file = "requirements.yml"
      ansible.galaxy_command = "ansible-galaxy collection install -r %{role_file}"
      ansible.vault_password_file = ".vault_pass"
    end
  end
end