{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coin-ops-credentials
  namespace: {{ .Values.namespaces.app }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: coin-ops-credentials
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ .Values.database.user }}:{{ `{{ .db_password }}` }}@coin-ops-db-rw.{{ .Values.namespaces.infra }}.svc.cluster.local:5432/{{ .Values.database.user }}"
        RABBITMQ_URL: "amqp://user:{{ `{{ .rabbitmq_password }}` }}@coin-ops-rabbitmq.{{ .Values.namespaces.infra }}.svc.cluster.local:5672/"
        REDIS_URL: "redis://:{{ `{{ .redis_password }}` }}@coin-ops-redis-master.{{ .Values.namespaces.infra }}.svc.cluster.local:6379"
  data:
    - secretKey: db_password
      remoteRef:
        key: coinops-db-password
    - secretKey: rabbitmq_password
      remoteRef:
        key: coinops-rabbitmq-password
    - secretKey: redis_password
      remoteRef:
        key: coinops-redis-password
{{- end }}
