---
# CoinOps React UI.
# Role variables are prefixed with coinops_ui_ by convention.

coinops_ui_kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config', true) | expanduser }}"
coinops_ui_namespace: coinops-frontend
coinops_ui_app_name: coinops-ui
coinops_ui_replicas: 2
coinops_ui_image_registry: ghcr.io/ua-academy-projects
coinops_ui_image_name: coin-ops-ui
coinops_ui_image_tag: dev-latest
coinops_ui_image: "{{ coinops_ui_image_registry }}/{{ coinops_ui_image_name }}:{{ coinops_ui_image_tag }}"
coinops_ui_container_port: 80
coinops_ui_service_port: 80
coinops_ui_proxy_url: /api
coinops_ui_history_url: /history-api
coinops_ui_image_pull_secret_name: ghcr-pull-secret
