NODES = {
  'web-ui' => {
    hostname: 'web-ui',
    ip: '192.168.56.10',
    cpu: 1,
    ram: 1024
  },
  'api-proxy' => {
    hostname: 'api-proxy',
    ip: '192.168.56.11',
    cpu: 1,
    ram: 512
  },
  'msg-queue' => {
    hostname: 'msg-queue',
    ip: '192.168.56.13',
    cpu: 1,
    ram: 1536
  },
  'history-svc' => {
    hostname: 'history-svc',
    ip: '192.168.56.14',
    cpu: 2,
    ram: 2048 
  },
  'db-server' => {
    hostname: 'db-server',
    ip: '192.168.56.12',
    cpu: 2, 
    ram: 2048
  }
}

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"

  config.vm.provision "shell", inline: "apt-get update"

  NODES.each do |name, cfg|
    config.vm.define name do |node|
      node.vm.hostname = cfg[:hostname]
      node.vm.network "private_network", ip: cfg[:ip]

      node.vm.provider "vmware_desktop" do |v|
        v.gui = false
        v.cpus = cfg[:cpu]
        v.memory = cfg[:ram]
      end
    end
  end
end
