locals {
  ansible_inventory_groups = distinct([for node in values(local.nodes) : node.role])

  ansible_inventory = trimspace(join("\n\n", concat(
    [
      "# Generated by Terraform. Do not edit by hand.",
    ],
    [
      for group in local.ansible_inventory_groups : join("\n", concat(
        ["[${group}]"],
        [
          for name, node in local.nodes :
          "softserve-${name} ansible_host=${node.ip}"
          if node.role == group
        ]
      ))
    ],
    [
      join("\n", [
        "[all:vars]",
        "ansible_user=${var.ansible_user}",
      ])
    ]
  )))
}

resource "local_file" "ansible_inventory" {
  filename = "${path.module}/${var.ansible_inventory_path}"
  content  = "${local.ansible_inventory}\n"
}
