#SPDX-License-Identifier: MIT-0
---
# defaults file for /tmp/role_skeleton
proxy_db_name: cognitor
proxy_db_user: cognitor
proxy_runtime_backend: "{{ lookup('env', 'RUNTIME_BACKEND') | default('external', true) }}"
proxy_rabbitmq_user: cognitor
proxy_rabbitmq_url: "amqp://{{ proxy_rabbitmq_user }}:{{ rabbitmq_password }}@{{ hostvars[groups['history'][0]].private_ip }}:5672/"
proxy_redis_url: "redis://redis:6379/0"
proxy_external_db_host: "{{ lookup('env', 'EXTERNAL_DB_HOST') | default('', true) }}"
proxy_database_host: "{{ proxy_external_db_host if proxy_external_db_host | length > 0 else hostvars[groups['history'][0]].private_ip }}"
proxy_database_url: "postgresql://{{ proxy_db_user }}:{{ db_password }}@{{ proxy_database_host }}:5432/{{ proxy_db_name }}"
proxy_port: 8080
proxy_image_registry: "{{ lookup('env', 'IMAGE_REGISTRY') | default('ghcr.io/ua-academy-projects', true) }}"
proxy_image_tag: "{{ lookup('env', 'IMAGE_TAG') | default('shabat-latest', true) }}"
proxy_image: "{{ proxy_image_registry }}/coin-ops-proxy:{{ proxy_image_tag }}"
