# Database variables for VM provisioning (Passwords are in vault.yml)
pg_host: "10.10.1.6"
pg_port: "5432"
pg_database: "coinops_db"
pg_version: "16"
pg_allowed_networks:
  - "10.10.1.0/24"

# External API Configurations
nbu_api_url: "https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json"
coingecko_api_url: "https://api.coingecko.com/api/v3/simple/price?ids=%s&vs_currencies=usd"
coingecko_ids: "bitcoin,ethereum,cardano,solana,ripple"
