- name: install rabbitmq packages
  ansible.builtin.apt:
    name:
      - rabbitmq-server
    state: present
    update_cache: true

- name: ensure rabbimq is running
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: true

# for checking queues, connections  
- name: enable rabbitmq management plugin
  become: true
  ansible.builtin.command: rabbitmq-plugins enable rabbitmq_management

- name: create rabbitmq user
  become: true
  ansible.builtin.command: rabbitmqctl add_user {{rabbitmq_user}} {{rabbitmq_password}}
  register: rabbitmq_add_user
  # rc - return code stderr - standard error
  # 0 - suceess != - failure
  failed_when: rabbitmq_add_user.rc != 0 and "already exists" not in rabbitmq_add_user.stderr
  changed_when: rabbitmq_add_user.rc == 0     # rc == 0 app finished successfully
 

- name: set rabbitmq permissions
  become: true
  ansible.builtin.command: rabbitmqctl set_permissions -p / {{rabbitmq_user}} ".*" ".*" ".*"

- name: set rabbitmq user tags
  become: true
  ansible.builtin.command: rabbitmqctl set_user_tags {{rabbitmq_user}} administrator