---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-consumer
  namespace: {{ .Values.namespaces.historyConsumer }}
  labels:
    app: history-consumer
    {{- include "coinops.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-consumer
  template:
    metadata:
      labels:
        app: history-consumer
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: history-consumer
          image: {{ .Values.image.registry }}/coin-ops-history-consumer:{{ .Values.image.tag }}
          envFrom:
            - secretRef:
                name: coinops-app-secret
