---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespaces.rabbitmq }}
  labels:
    app: rabbitmq
    {{- include "coinops.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      automountServiceAccountToken: false
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: {{ .Values.ports.rabbitmq }}
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: coinops-rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: coinops-rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespaces.rabbitmq }}
  labels:
    {{- include "coinops.labels" . | nindent 4 }}
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.ports.rabbitmq }}
      targetPort: {{ .Values.ports.rabbitmq }}
    - name: management
      port: 15672
      targetPort: 15672
