---
- name: Deploy Homepage into K3s
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: gcp_secret_values
      vars:
        gcp_secret_values_load_cloudflare_token: true
    - homepage
