apiVersion: v1
kind: ConfigMap
metadata:
  name: coin-ops-config
  namespace: coin-ops
  labels:
    app.kubernetes.io/part-of: coin-ops
data:
  RUNTIME_BACKEND: external
  HISTORY_API_PORT: "8000"
  PROXY_PORT: "8080"
  PROXY_URL: /api
  HISTORY_URL: /history-api
