# align timezone settings for postgres and vm
- name: install time sync packages
  ansible.builtin.apt:
    name:
      - chrony
    state: present
    update_cache: true
  

- name: ensure chrony is running
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true

- name: set timezone 
  community.general.timezone:
    name: Europe/Kyiv


- name: install postgres packages
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present
    update_cache: true

- name: ensure postgres is running
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true


- name: configure correct db data time
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    regexp: '^#?timezone\s*='
    line: "timezone = 'Europe/Kyiv'"
  notify: restart postgres



- name: configure postgres listen addresses
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '{{postgres_host}}'"
  notify: restart postgresql

- name: allow connections from vagrant network
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/16/main/pg_hba.conf
    line: "host   all   all   192.168.56.0/24 scram-sha-256"
  notify: restart postgresql  # notify handler

- name: apply postgres config changes now
  meta: flush_handlers
  

- name: create db 
  community.postgresql.postgresql_db:
    name: "{{postgres_db}}"
    state: present
    
    # postgreSQL admin user authentication 
    login_host: "{{postgres_host}}"
    login_user: "{{pgadmin_login}}"
    login_password: "{{pgadmin_login_password}}"

- name: create db user
  community.postgresql.postgresql_user:
    name: "{{postgres_user}}"
    password: "{{postgres_password}}"
    state: present

    login_host: "{{postgres_host}}"
    login_user: "{{pgadmin_login}}"
    login_password: "{{pgadmin_login_password}}"


- name: create db table
  community.postgresql.postgresql_table:
    login_db: "{{postgres_db}}"
    name: "{{postgres_table}}"
    columns:
      - id serial primary key
      - coin varchar(10) not null
      - price numeric(15,2) not null
      - recorded_at timestamp default now()

    login_host: "{{postgres_host}}"
    login_user: "{{pgadmin_login}}"
    login_password: "{{pgadmin_login_password}}"

# grant access to db
- name: grant database privileges
  community.postgresql.postgresql_privs:
    login_db: "{{postgres_db}}"
    type: database
    privs: ALL
    roles: "{{postgres_user}}"
    objs: "{{postgres_db}}"
  
    login_host: "{{postgres_host}}"
    login_user: "{{pgadmin_login}}"
    login_password: "{{pgadmin_login_password}}"


# grant access to schema
- name: grant app user access to public schema
  community.postgresql.postgresql_privs:
    login_db: "{{postgres_db}}"
    type: schema
    objs: public  # schema name
    privs: USAGE,CREATE
    roles: "{{postgres_user}}"

  
    login_host: "{{postgres_host}}"
    login_user: "{{pgadmin_login}}"
    login_password: "{{pgadmin_login_password}}"


- name: grant table privileges
  community.postgresql.postgresql_privs:
    login_db: "{{ postgres_db }}"
    type: table
    schema: public
    objs: "{{ postgres_table }}"
    privs: SELECT,INSERT,UPDATE,DELETE
    roles: "{{ postgres_user }}"

    login_host: "{{postgres_host}}"
    login_user: "{{pgadmin_login}}"
    login_password: "{{pgadmin_login_password}}"


# for auto generating id's
- name: grant sequence privileges
  community.postgresql.postgresql_privs:
    login_db: "{{ postgres_db }}"
    type: sequence
    schema: public
    objs: "{{ postgres_table }}_id_seq"
    privs: USAGE,SELECT,UPDATE
    roles: "{{ postgres_user }}"

    login_host: "{{postgres_host}}"
    login_user: "{{pgadmin_login}}"
    login_password: "{{pgadmin_login_password}}"


 
