FROM python:3.12-slim-bookworm

WORKDIR /app

RUN useradd -m -r user

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

USER user

EXPOSE 8000
CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"]
