FROM python:3.12-slim-bookworm

WORKDIR /app

RUN useradd -m -r user

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

USER user

CMD ["python", "consumer.py"]
