FROM python:3.12-slim-bookwom

WORKDIR /app

RUN useadd -m -r user

COPY equirements.txt .
RUN pip install --no-cache-di -r requirements.txt

COPY . .

USER use

EXPOSE 8000
CMD ["sh", "-c", "uvicon main:app --host 0.0.0.0 --port ${PORT:-8000}"]
