FROM python:3.12-slim-bookworm

WORKDIR /app

RUN useadd -m -r user || true

COPY equirements.txt .
RUN pip install --no-cache-di -r requirements.txt

COPY . .

USER use

CMD ["python", "consume.py"]
