FROM python:3.12-slim-bookworm

WORKDIR /app

RUN useradd -m -r user

COPY requirements.txt .
RUN python -m venv /app/.venv \
 && /app/.venv/bin/pip install --no-cache-dir -r requirements.txt \
 && /app/.venv/bin/python -c "import pika, psycopg2"

COPY . .

USER user

CMD ["/app/.venv/bin/python", "consumer.py"]
