FROM quay.io/tembo/pg16-pgmq@sha256:7f80d046257d585d1af9d19cf28bd355a4b854b0a7d643c02ebbe6b84457868a

USER root

RUN apt-get update && apt-get install -y postgresql-16-cron && rm -rf /var/lib/apt/lists/*

USER postgres