---
- name: Install a joining k3s server
  command: >-
    {{ k3s_install_script_path }}
    server
    --server {{ k3s_first_server_url }}
    --token {{ hostvars[groups['k3s_first_server'][0]].k3s_node_token }}
    --tls-san {{ k3s_tls_san }}
    --node-ip {{ ansible_host }}
    --advertise-address {{ ansible_host }}
  environment:
    INSTALL_K3S_CHANNEL: "{{ k3s_channel }}"
  when: not k3s_service.stat.exists
  no_log: true

- name: Ensure k3s service is started and enabled
  systemd:
    name: k3s
    state: started
    enabled: yes

- name: Wait for the joined k3s API server
  wait_for:
    host: "{{ ansible_host }}"
    port: "{{ k3s_api_port }}"
    timeout: 180

