version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: proxy_user
      RABBITMQ_DEFAULT_PASS: proxy_password
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis

  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  history:
    build: ./history
    container_name: history
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "8080:8080"
    depends_on:
      - proxy

networks:
  default:
    name: coinops-network
