# ===== Builder stage =====
FROM python:3.12-slim AS builder

WORKDIR /build

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY consumer/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# ===== Runtime stage =====
FROM python:3.12-slim

WORKDIR /app

# Копіюємо готовий venv
COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1

# Копіюємо код
COPY consumer/consumer.py ./

EXPOSE 5001

CMD ["python", "consumer.py"]