apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coinops-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ua-academy-projects/coin-ops.git
    targetRevision: dev-Shabat-cloud
    path: charts/coinops-app
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: coinops-app-secrets
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: ghcr-pull
      jsonPointers:
        - /data
