#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/k3s_homepage

- name: Install Helm
  ansible.builtin.shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Install Python venv support 
# Needed for kubernetes.core.k8s
  ansible.builtin.apt:
    name:
      - python3-venv
      - python3-pip
    state: present

- name: Install Kubernetes Python client in venv
  ansible.builtin.pip:
    name: "kubernetes=={{ k3s_homepage_python_kubernetes_version }}"
    virtualenv: /opt/headlamp-ansible-venv
    virtualenv_command: python3 -m venv


