# SPDX-License-Identifier: MIT-0
---
# defaults file for k3s_coin_ops
k3s_coin_ops_release_name: coin-ops
k3s_coin_ops_chart_path: "{{ playbook_dir }}/../charts/coin-ops"
k3s_coin_ops_remote_chart_path: /opt/coin-ops-chart
k3s_coin_ops_values_file: /tmp/coin-ops-values.yaml
k3s_coin_ops_kubeconfig: /etc/rancher/k3s/k3s.yaml
k3s_coin_ops_ansible_venv_path: /opt/k3s-ansible-venv

k3s_coin_ops_namespaces:
  app: coin-ops-app
  workers: coin-ops-workers
  data: coin-ops-data

k3s_coin_ops_config_name: coin-ops-config
k3s_coin_ops_secret_name: coin-ops-secret
k3s_coin_ops_pull_secret_name: ghcr-pull-secret
k3s_coin_ops_ingress_host: coinops.arturvolynets.pp.ua
k3s_coin_ops_tls_enabled: true
k3s_coin_ops_tls_secret_name: coin-ops-tls
k3s_coin_ops_cluster_issuer: letsencrypt
k3s_coin_ops_image_tag: "{{ lookup('env', 'IMAGE_TAG') | default('shabat-latest', true) }}"

k3s_coin_ops_ghcr_server: ghcr.io
k3s_coin_ops_ghcr_username: "{{ fetched_gsm_secrets.ghcr_username | default(lookup('env', 'GHCR_USERNAME'), true) }}"
k3s_coin_ops_ghcr_token: "{{ fetched_gsm_secrets.ghcr_token | default(lookup('env', 'GHCR_TOKEN'), true) }}"
k3s_coin_ops_ghcr_email: "{{ lookup('env', 'GHCR_EMAIL') | default('', true) }}"
k3s_coin_ops_postgres_password: "{{ fetched_gsm_secrets.db_password | default(lookup('env', 'POSTGRES_PASSWORD'), true) }}"
k3s_coin_ops_rabbitmq_password: "{{ fetched_gsm_secrets.rabbitmq_password | default(lookup('env', 'RABBITMQ_PASSWORD'), true) }}"

k3s_coin_ops_postgres_user: "{{ lookup('env', 'POSTGRES_USER') | default('app', true) }}"
k3s_coin_ops_postgres_db: "{{ lookup('env', 'POSTGRES_DB') | default('app', true) }}"
k3s_coin_ops_postgres_host: "{{ lookup('env', 'POSTGRES_HOST') | default('postgres-rw.coin-ops-data.svc.cluster.local', true) }}"
k3s_coin_ops_postgres_port: "{{ lookup('env', 'POSTGRES_PORT') | default('5432', true) }}"
k3s_coin_ops_database_url: >-
  {{
    "postgresql://"
    ~ k3s_coin_ops_postgres_user
    ~ ":"
    ~ k3s_coin_ops_postgres_password
    ~ "@"
    ~ k3s_coin_ops_postgres_host
    ~ ":"
    ~ k3s_coin_ops_postgres_port
    ~ "/"
    ~ k3s_coin_ops_postgres_db
  }}

k3s_coin_ops_rabbitmq_user: "{{ lookup('env', 'RABBITMQ_USER') | default('cognitor', true) }}"
k3s_coin_ops_rabbitmq_url: >-
  {{
    "amqp://"
    ~ k3s_coin_ops_rabbitmq_user
    ~ ":"
    ~ k3s_coin_ops_rabbitmq_password
    ~ "@rabbitmq."
    ~ k3s_coin_ops_namespaces.data
    ~ ".svc.cluster.local:5672/"
  }}
