---
cert_manager_namespace: cert-manager
cert_manager_version: v1.20.2
cert_manager_manifest_url: "https://github.com/cert-manager/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.yaml"
cert_manager_kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default(lookup('env', 'HOME') ~ '/.kube/config', true) }}"
cluster_issuer_name: letsencrypt-prod
cluster_issuer_email: "{{ lookup('env', 'LETSENCRYPT_EMAIL') | default('val.don.ua@gmail.com', true) }}"
cluster_issuer_server: https://acme-v02.api.letsencrypt.org/directory
cluster_issuer_private_key_secret_name: "{{ cluster_issuer_name }}-account-key"
cluster_issuer_ingress_class_name: traefik
cluster_issuer_kubeconfig: "{{ cert_manager_kubeconfig }}"
