---
common_allowed_ports:
  - "{{ infra_general.get('ssh_port', 53725) }}"
  - "{{ infra_ports.get('postgres', 5432) }}"
  - "{{ infra_ports.get('rabbitmq', 5672) }}"
  - "{{ infra_ports.get('rabbitmq_management', 15672) }}"
  - "{{ infra_ports.get('history', 8000) }}"
  - "{{ infra_ports.get('proxy', 8080) }}"
  - "{{ infra_deploy.get('internal_tls', {}).get('port', 8443) }}"
