# SPDX-License-Identifier: MIT-0

---
# tasks file for ansible/roles/k3s_gateway
- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true

- name: Enable and start HAProxy
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
    state: started

- name: Deploy HAProxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Restart HAProxy
