apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coin-ops.fullname" . }}-config
  labels:
{{ include "coin-ops.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
