apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coin-ops.fullname" . }}
  labels:
{{ include "coin-ops.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.maxUnavailable }}
      maxSurge: {{ .Values.updateStrategy.maxSurge }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "coin-ops.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "coin-ops.labels" . | indent 8 }}
    spec:
      containers:
        - name: coin-ops
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "coin-ops.fullname" . }}-config
            - secretRef:
                name: {{ include "coin-ops.fullname" . }}-secret
          env:
            - name: PROXY_UPSTREAM
              value: "http://{{ include "coin-ops.fullname" . }}-proxy:{{ .Values.proxy.service.port }}/"
            - name: HISTORY_UPSTREAM
              value: "http://{{ include "coin-ops.fullname" . }}-history-api:{{ .Values.historyApi.service.port }}/"
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
