{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "coin-ops.fullname" . }}
  labels:
{{ include "coin-ops.labels" . | indent 4 }}
  annotations:
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "coin-ops.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
{{- end }}
