apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coin-ops.fullname" . }}-secret
  labels:
{{ include "coin-ops.labels" . | indent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
