{{if .Values.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress   # ingress always listens on 80/443
metadata:
  name: coinops
  namespace: {{.Release.Namespace}}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: {{.Values.ingress.ingressClassName}}
  # tell traefik to use HTTPS for this host
  tls:  
    - hosts:
        - {{.Values.ingress.domain}}
      secretName: coinops-tls
  rules:
    - host: {{.Values.ingress.domain}}  # only match request for app.coin-ops.pp.ua
      http:
        paths:
          - path: / # match any path starting with /
            pathType: Prefix    # match everything / (/, /api, /history-api)
            backend:
              service:
                name: {{.Values.ui.name}}
                port:
                  number: {{.Values.ui.port}}    # ui service on port 80
          - path: /api
            pathType: Prefix
            backend: 
              service:
                name: {{.Values.proxy.name}}
                port:
                  number: {{.Values.proxy.port}}
          - path: /history-api
            pathType: Prefix
            backend:
              service:
                name: {{.Values.historyApi.name}}
                port:
                  number: {{.Values.historyApi.port}}
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: {{.Values.proxy.name}}
                port:
                  number: {{.Values.proxy.port}}
{{end}}