# =============================================================================
# k3s/secrets.tf
# =============================================================================
# All cluster secrets are stored in GCP Secret Manager.
# Terraform creates and manages the secret shells; secret VALUES are written:
#
#   k3s-cluster-token    ← written by bootstrap/k3s-bootstrap.sh on first run
#   k3s-ssh-private-key  ← generated by Terraform (tls_private_key) and stored
#   k3s-ssh-public-key   ← companion public key, consumed by compute.tf
#
# Data flow:
#   terraform apply
#     → tls_private_key.k3s_ssh generated in memory
#     → stored as a Secret Manager version (k3s-ssh-private-key)
#     → public key stored as k3s-ssh-public-key
#     → k3s-cluster-token read back via data source → injected into cloud-init
#
# Secret naming convention: k3s-<cluster>-<secret> for easy IAM scoping.
#
# NEVER add secret values to configs/*.json, tfvars, or source control.
# =============================================================================

# ─── Enable Secret Manager API (idempotent) ───────────────────────────────────
resource "google_project_service" "secretmanager" {
  project            = local.project_id
  service            = "secretmanager.googleapis.com"
  disable_on_destroy = false
}

# ═════════════════════════════════════════════════════════════════════════════
# k3s Cluster Token
# Created externally (bootstrap script) and read back here.
# If the secret doesn't exist yet, terraform plan will error clearly.
# ═════════════════════════════════════════════════════════════════════════════

# Create the secret shell (idempotent — Terraform manages the resource, not
# the value; the value is set by the bootstrap script or CI/CD pipeline).
resource "google_secret_manager_secret" "k3s_token" {
  project   = local.project_id
  secret_id = "k3s-cluster-token"

  replication {
    user_managed {
      replicas {
        location = local.region
      }
    }
  }

  labels = local.common_labels

  depends_on = [google_project_service.secretmanager]
}

# Read the current latest version of the token at plan time.
# This fails loudly if no version exists yet — intentional: run the
# bootstrap script first (see bootstrap/k3s-bootstrap.sh).
data "google_secret_manager_secret_version" "k3s_token" {
  project = local.project_id
  secret  = google_secret_manager_secret.k3s_token.secret_id
  version = "latest"
}

# ═════════════════════════════════════════════════════════════════════════════
# SSH Key Pair (Terraform-generated, stored in Secret Manager)
# ═════════════════════════════════════════════════════════════════════════════

# Generate an ephemeral RSA-4096 key pair in Terraform state.
# The private key is immediately stored in Secret Manager and the local
# Terraform state value is marked sensitive.
resource "tls_private_key" "k3s_ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

# ── Secret: private key ───────────────────────────────────────────────────────
resource "google_secret_manager_secret" "k3s_ssh_private_key" {
  project   = local.project_id
  secret_id = "k3s-ssh-private-key"

  replication {
    user_managed {
      replicas {
        location = local.region
      }
    }
  }

  labels = local.common_labels
  depends_on = [google_project_service.secretmanager]
}

resource "google_secret_manager_secret_version" "k3s_ssh_private_key" {
  secret      = google_secret_manager_secret.k3s_ssh_private_key.id
  secret_data = tls_private_key.k3s_ssh.private_key_pem

  # Destroy old versions when Terraform replaces the key
  lifecycle {
    create_before_destroy = true
  }
}

# ── Secret: public key ────────────────────────────────────────────────────────
resource "google_secret_manager_secret" "k3s_ssh_public_key" {
  project   = local.project_id
  secret_id = "k3s-ssh-public-key"

  replication {
    user_managed {
      replicas {
        location = local.region
      }
    }
  }

  labels = local.common_labels
  depends_on = [google_project_service.secretmanager]
}

resource "google_secret_manager_secret_version" "k3s_ssh_public_key" {
  secret      = google_secret_manager_secret.k3s_ssh_public_key.id
  secret_data = tls_private_key.k3s_ssh.public_key_openssh

  lifecycle {
    create_before_destroy = true
  }
}

# ═════════════════════════════════════════════════════════════════════════════
# IAM — Grant k3s nodes read access to their own secrets only
# ═════════════════════════════════════════════════════════════════════════════

# k3s node SA can read the cluster token (needed for cloud-init join)
resource "google_secret_manager_secret_iam_member" "k3s_node_reads_token" {
  project   = local.project_id
  secret_id = google_secret_manager_secret.k3s_token.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.k3s_node.email}"
}

# k3s node SA can read its own public key (for node enrollment scripts)
resource "google_secret_manager_secret_iam_member" "k3s_node_reads_pubkey" {
  project   = local.project_id
  secret_id = google_secret_manager_secret.k3s_ssh_public_key.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.k3s_node.email}"
}

# ═════════════════════════════════════════════════════════════════════════════
# Tailscale Operator Secrets
# ═════════════════════════════════════════════════════════════════════════════

resource "google_secret_manager_secret" "tailscale_oauth_id" {
  project   = local.project_id
  secret_id = "tailscale-oauth-client-id"

  replication {
    user_managed {
      replicas {
        location = local.region
      }
    }
  }

  labels = local.common_labels
  depends_on = [google_project_service.secretmanager]
}

data "google_secret_manager_secret_version" "tailscale_oauth_id" {
  project = local.project_id
  secret  = google_secret_manager_secret.tailscale_oauth_id.secret_id
  version = "latest"
}

resource "google_secret_manager_secret" "tailscale_oauth_secret" {
  project   = local.project_id
  secret_id = "tailscale-oauth-client-secret"

  replication {
    user_managed {
      replicas {
        location = local.region
      }
    }
  }

  labels = local.common_labels
  depends_on = [google_project_service.secretmanager]
}

data "google_secret_manager_secret_version" "tailscale_oauth_secret" {
  project = local.project_id
  secret  = google_secret_manager_secret.tailscale_oauth_secret.secret_id
  version = "latest"
}
