
- name: Install platform components on AKS
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: traefik_install
      tags:
        - traefik
        - ingress

    - role: cert_manager
      tags:
        - cert-manager
        - tls

    - role: cert_manager_issuer
      tags:
        - issuer
        - tls

    - role: jenkins_install
      tags:
        - jenkins
        - cicd
