- name: Setup NBU Collector
  hosts: aplication
  become: yes

  vars:
    go_version: "1.22.3"
    app_dir: /app

  tasks:
    # ------------------------
    # System update + deps
    # ------------------------
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - curl
          - git
          - rabbitmq-server
        state: present

    # ------------------------
    # Install Go
    # ------------------------
    - name: Check if Go is installed
      command: /usr/local/go/bin/go version
      register: go_check
      ignore_errors: yes
      changed_when: false

    - name: Download Go
      get_url:
        url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "/tmp/go{{ go_version }}.tar.gz"
      when: go_check.failed

    - name: Remove old Go
      file:
        path: /usr/local/go
        state: absent
      when: go_check.failed

    - name: Extract Go
      unarchive:
        src: "/tmp/go{{ go_version }}.tar.gz"
        dest: /usr/local
        remote_src: yes
      when: go_check.failed

    - name: Add Go to PATH
      lineinfile:
        path: /etc/profile
        line: "export PATH=$PATH:/usr/local/go/bin"
        state: present

    # ------------------------
    # RabbitMQ
    # ------------------------
    - name: Enable RabbitMQ
      service:
        name: rabbitmq-server
        enabled: yes
        state: started

    # ------------------------
    # Build app
    # ------------------------
    - name: Ensure app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
    - name: Copy app files
      copy:
        src: ./app/
        dest: "{{ app_dir }}"
    - name: Run go mod tidy
      command: /usr/local/go/bin/go mod tidy
      args:
        chdir: "{{ app_dir }}"

    - name: Build Go app
      command: /usr/local/go/bin/go build -o nbu-collector
      args:
        chdir: "{{ app_dir }}"

    # ------------------------
    # Systemd service
    # ------------------------
    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/nbu-collector.service
        content: |
          [Unit]
          Description=NBU Collector
          After=network.target rabbitmq-server.service

          [Service]
          WorkingDirectory=/app
          ExecStart=/app/nbu-collector

          Environment="PUBLISH_MODE=rabbit"
          Environment="DRY_RUN=false"
          Environment="RABBITMQ_URL=amqp://guest:guest@localhost:5672/"
          Environment="RABBITMQ_QUEUE=nbu.exchange.rates"
          Environment="HTTP_ADDR=:8080"

          Restart=always
          RestartSec=5
          User=vagrant

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start app
      systemd:
        name: nbu-collector
        enabled: yes
        state: started
