[ui]
devops-ui ansible_host=192.168.56.11

[proxy]
devops-proxy ansible_host=192.168.56.12

[history]
devops-history ansible_host=192.168.56.13

[data]
devops-data ansible_host=192.168.56.14 

[all:vars]
# set ssh user by default for all hosts
ansible_user=vagrant

