# provision k3s cluster with coin-ops application

---
- name: Provision k3s gateway
  hosts: bastion
  become: true
  roles:
    - role: common
      tags: common
    - role: nat
      tags: nat
    - role: k3s_gateway
      tags: gateway

- name: Provision k3s cluster
  hosts: k3s
  become: true
  roles:
    - role: common
      tags: common
    - role: k3s_cluster
      tags: k3s

- name: Install k3s Helm dependencies
  hosts: k3s-node-01
  become: true
  roles:
    - role: k3s_helm
      tags:
        - helm
        - cert-manager
        - headlamp
        - cnpg
        - coin-ops

- name: Deploy cert-manager
  hosts: k3s-node-01
  become: true
  roles:
    - role: k3s_cert_manager
      tags: cert-manager

- name: Deploy Headlamp
  hosts: k3s-node-01
  become: true
  roles:
    - role: k3s_headlamp
      tags: headlamp

- name: Fetch deploy secrets from Azure Key Vault
  hosts: k3s-node-01
  become: true
  roles:
    - role: azure_secrets
      tags:
        - secrets
        - coin-ops
      when:
        - cloud == 'azure'

- name: Fetch deploy secrets from Google Secret Manager
  hosts: k3s-node-01
  become: true
  roles:
    - role: gsm_secrets
      tags:
        - secrets
        - coin-ops
      when:
        - cloud == 'gcp'

- name: Fetch deploy secrets from AWS Secrets Manager
  hosts: k3s-node-01
  become: true
  roles:
    - role: aws_secrets
      tags:
        - secrets
        - coin-ops
      when:
        - cloud == 'aws'

- name: Deploy CNPG
  hosts: k3s-node-01
  become: true
  roles:
    - role: k3s_cnpg
      tags: cnpg

- name: Deploy Coin Ops
  hosts: k3s-node-01
  become: true
  roles:
    - role: k3s_coin_ops
      tags: coin-ops
