---
# tasks file for history_service
- name: Install history_service packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - python3-flask
    state: present
    update_cache: yes

- name: Setup python environment
  pip:
    requirements: /home/vagrant/shared_folder/history_service/requirements.txt
    virtualenv: /home/vagrant/venv
    virtualenv_command: /usr/bin/python3 -m venv

- name: Copy history_service systemd unit file to remote host
  copy:
    src: history_service.service
    dest: /etc/systemd/system/history_service.service
    mode: '0644'
  notify: Restart History Service

- name: Setup systemd history_service service
  systemd:
    name: history_service
    enabled: yes
    state: started
    daemon_reload: yes
