#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/k3s_cluster

- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  become: true

- name: Check if k3s is installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Install k3s primary
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server \
      --cluster-init \
      --node-ip={{ hostvars[inventory_hostname][k3s_cluster_node_ip] }} \
      --advertise-address={{ hostvars[inventory_hostname][k3s_cluster_node_ip] }}" sh -
  when:
    - not k3s_binary.stat.exists
    - inventory_hostname == k3s_cluster_primary_node

- name: Wait for k3s cluster token on primary
  ansible.builtin.wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    timeout: 120
  delegate_to: "{{ k3s_cluster_primary_node }}"
  run_once: true

- name: Get k3s cluster token from primary
  ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  changed_when: false
  delegate_to: "{{ k3s_cluster_primary_node }}"
  run_once: true

- name: Install k3s secondary
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | K3S_TOKEN="{{ k3s_token.stdout }}" INSTALL_K3S_EXEC="server \
      --server https://{{ hostvars[k3s_cluster_primary_node][k3s_cluster_node_ip] }}:6443 \
      --node-ip={{ hostvars[inventory_hostname][k3s_cluster_node_ip] }} \
      --advertise-address={{ hostvars[inventory_hostname][k3s_cluster_node_ip] }}" sh -
  when:
    - not k3s_binary.stat.exists
    - inventory_hostname != k3s_cluster_primary_node
