{{- range $ns := list .Values.proxy.namespace .Values.historyApi.namespace .Values.historyConsumer.namespace .Values.ui.namespace .Values.gateway.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
    coinops-tier: app
    {{- include "coinops-app.labels" $ | nindent 4 }}
{{- end }}
