- name: install proxy packages
  ansible.builtin.apt:
    name: 
      - python3
      - python3-flask
      - python3-requests
      - python3-pika

    state: present
    update_cache: true

- name: install proxy systemd unit
  become: true
  ansible.builtin.template:
    src: proxy.service.j2
    dest: /etc/systemd/system/proxy.service 

  notify: reload systemd

- meta: flush_handlers
- name: enable and start proxy service
  become: true
  ansible.builtin.systemd:
    name: proxy
    enabled: true
    state: restarted
