name: Infrastructure Validation

on:
  workflow_dispatch:
  push:
      branches:
        - volynets-infra-dev

permissions:
  contents: read

jobs:
  config:
    name: Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
  ansible:
    name: Ansible
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
  shell:
    name: Shell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
